project:
  type: website
  output-dir: docs

website:
  title: "git-git-github!!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Intro
      - href: github.qmd
        text: GitHub
      - href: begit.qmd
        text: Be-Git
      - href: gogit.qmd
        text: Beyond-Git
      - href: gogithub.qmd
        text: Go-GitHub
    right:
      - icon: github
        href: https://github.com/zchuri/gitgitgithub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

